# Generated by Django 2.0.2 on 2021-05-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=100)),
                ('manifest', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteSum', models.IntegerField(default=0)),
                ('politicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Politic')),
            ],
        ),
    ]
