# Generated by Django 2.0.2 on 2021-06-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='politicID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hello.Politic'),
        ),
    ]
