# Generated by Django 2.0.2 on 2021-06-05 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AREA',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('modeifiedDateTime', models.DateTimeField(auto_now=True)),
                ('areaName', models.CharField(max_length=20, verbose_name='選挙区名')),
                ('areaNameKana', models.CharField(max_length=40, verbose_name='選挙区名かな')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CANDIDATE',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('modeifiedDateTime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='立候補者名')),
                ('nameKN', models.CharField(max_length=40, verbose_name='立候補者名カナ')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, '男性'), (1, '女性'), (2, 'other')], verbose_name='性別')),
                ('birthYMD', models.DateField(verbose_name='生年月日')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('link', models.URLField(blank=True, null=True, verbose_name='リンク')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ELECTION',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('modeifiedDateTime', models.DateTimeField(auto_now=True)),
                ('electionCd', models.PositiveSmallIntegerField(verbose_name='選挙コード')),
                ('electionName', models.CharField(max_length=20, verbose_name='選挙名')),
                ('electionNameKana', models.CharField(max_length=40, verbose_name='選挙名カナ')),
                ('startYMD', models.DateField(verbose_name='開始日')),
                ('endYMD', models.DateField(verbose_name='終了日')),
                ('topPageFLG', models.BooleanField(default=False, verbose_name='トップページフラグ')),
                ('areaCd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queen.AREA', verbose_name='選挙区')),
                ('candidateCd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queen.CANDIDATE', verbose_name='立候補者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('modeifiedDateTime', models.DateTimeField(auto_now=True)),
                ('image', models.FilePathField(verbose_name='画像ファイルパス')),
                ('candidateCd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queen.CANDIDATE', verbose_name='立候補者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PARTY',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('modeifiedDateTime', models.DateTimeField(auto_now=True)),
                ('partyName', models.CharField(max_length=20, verbose_name='政党名')),
                ('partyNameKN', models.CharField(max_length=40, verbose_name='政党名カナ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VOTE',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('modeifiedDateTime', models.DateTimeField(auto_now=True)),
                ('totalCount', models.PositiveIntegerField(verbose_name='得票数')),
                ('maleCount', models.PositiveIntegerField(verbose_name='男性得票数')),
                ('femaleCount', models.PositiveIntegerField(verbose_name='女性得票数')),
                ('underEighteenCount', models.PositiveIntegerField(verbose_name='未成年得票数')),
                ('overEighteenCount', models.PositiveIntegerField(verbose_name='成年得票数')),
                ('candidateCd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queen.CANDIDATE', verbose_name='立候補者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='partyCd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queen.PARTY', verbose_name='所属'),
        ),
    ]
