# Generated by Django 2.0.2 on 2021-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '選挙区', 'verbose_name_plural': '選挙区'},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': '立候補者', 'verbose_name_plural': '立候補者'},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'verbose_name': '選挙', 'verbose_name_plural': '選挙'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '画像', 'verbose_name_plural': '画像'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': '政党', 'verbose_name_plural': '政党'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': '投票', 'verbose_name_plural': '投票'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='画像ファイル'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='femaleCount',
            field=models.PositiveIntegerField(default=0, verbose_name='女性得票数'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='maleCount',
            field=models.PositiveIntegerField(default=0, verbose_name='男性得票数'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='overEighteenCount',
            field=models.PositiveIntegerField(default=0, verbose_name='成年得票数'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='totalCount',
            field=models.PositiveIntegerField(default=0, verbose_name='得票数'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='underEighteenCount',
            field=models.PositiveIntegerField(default=0, verbose_name='未成年得票数'),
        ),
        migrations.AlterModelTable(
            name='area',
            table='AREA',
        ),
        migrations.AlterModelTable(
            name='candidate',
            table='CANDIDATE',
        ),
        migrations.AlterModelTable(
            name='election',
            table='ELECTION',
        ),
        migrations.AlterModelTable(
            name='image',
            table='IMAGE',
        ),
        migrations.AlterModelTable(
            name='party',
            table='PARTY',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='VOTE',
        ),
    ]
