# Generated by Django 2.0.2 on 2021-06-05 08:52

from django.db import migrations


class Migration(migrations.Migration):
    
    atomic = False

    dependencies = [
        ('queen', '0002_auto_20210605_1726'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table=None,
        ),
        migrations.AlterModelTable(
            name='candidate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='election',
            table=None,
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='party',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vote',
            table=None,
        ),
    ]
