# Generated by Django 2.0.2 on 2021-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    
    atomic = False

    dependencies = [
        ('queen', '0003_auto_20210605_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='areaNameKana',
            field=models.CharField(max_length=40, verbose_name='選挙区名カナ'),
        ),
    ]
